[redis]
[redis.standalone]
host="localhost"
port=6379

[email]
email="noreply@vastsea.com"
[email.transport]
host="sandbox.smtp.mailtrap.io"
port=2525
[email.transport.auth]
user="70589292a368c5"
pass="6128fa467c17be"