name: Build Dry Run

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.10.0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
          cache-dependency-path: packages/backend/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: packages/backend
        run: pnpm i
      - name: Build
        working-directory: packages/backend
        run: pnpm build