name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run-install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install backend dependencies
        working-directory: packages/backend
        run: pnpm i --frozen-lockfile --prefer-offline
      - name: Install frontend dependencies
        working-directory: packages/frontend
        run: pnpm i --frozen-lockfile --prefer-offline
      - name: Run linters backend
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          eslint_dir: packages/backend
          prettier_dir: packages/backend
      - name: Run linters frontend
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          eslint_dir: packages/frontend
          prettier_dir: packages/frontend